package sunaba.godot;

import sunaba.core.Event;

@:native("godot.NavigationServer3D")
extern class NavigationServer3D extends Object {
    @:native("__new")
    public function new();
    public function agentCreate(): RID;
    public function agentGetAvoidanceEnabled(agent: RID): Bool;
    public function agentGetAvoidanceLayers(agent: RID): Int;
    public function agentGetAvoidanceMask(agent: RID): Int;
    public function agentGetAvoidancePriority(agent: RID): Float;
    public function agentGetHeight(agent: RID): Float;
    public function agentGetMap(agent: RID): RID;
    public function agentGetMaxNeighbors(agent: RID): Int;
    public function agentGetMaxSpeed(agent: RID): Float;
    public function agentGetNeighborDistance(agent: RID): Float;
    public function agentGetPaused(agent: RID): Bool;
    public function agentGetPosition(agent: RID): Vector3;
    public function agentGetRadius(agent: RID): Float;
    public function agentGetTimeHorizonAgents(agent: RID): Float;
    public function agentGetTimeHorizonObstacles(agent: RID): Float;
    public function agentGetUse3dAvoidance(agent: RID): Bool;
    public function agentGetVelocity(agent: RID): Vector3;
    public function agentHasAvoidanceCallback(agent: RID): Bool;
    public function agentIsMapChanged(agent: RID): Bool;
    public function agentSetAvoidanceCallback(agent: RID, callback: Callable): Void;
    public function agentSetAvoidanceEnabled(agent: RID, enabled: Bool): Void;
    public function agentSetAvoidanceLayers(agent: RID, layers: Int): Void;
    public function agentSetAvoidanceMask(agent: RID, mask: Int): Void;
    public function agentSetAvoidancePriority(agent: RID, priority: Float): Void;
    public function agentSetHeight(agent: RID, height: Float): Void;
    public function agentSetMap(agent: RID, map: RID): Void;
    public function agentSetMaxNeighbors(agent: RID, count: Int): Void;
    public function agentSetMaxSpeed(agent: RID, maxSpeed: Float): Void;
    public function agentSetNeighborDistance(agent: RID, distance: Float): Void;
    public function agentSetPaused(agent: RID, paused: Bool): Void;
    public function agentSetPosition(agent: RID, position: GdVector3): Void;
    public function agentSetRadius(agent: RID, radius: Float): Void;
    public function agentSetTimeHorizonAgents(agent: RID, timeHorizon: Float): Void;
    public function agentSetTimeHorizonObstacles(agent: RID, timeHorizon: Float): Void;
    public function agentSetUse3dAvoidance(agent: RID, enabled: Bool): Void;
    public function agentSetVelocity(agent: RID, velocity: GdVector3): Void;
    public function agentSetVelocityForced(agent: RID, velocity: GdVector3): Void;
    public function bakeFromSourceGeometryData(navigationMesh: NavigationMesh, sourceGeometryData: NavigationMeshSourceGeometryData3D, ?callback: Callable): Void;
    public function bakeFromSourceGeometryDataAsync(navigationMesh: NavigationMesh, sourceGeometryData: NavigationMeshSourceGeometryData3D, ?callback: Callable): Void;
    public function freeRid(rid: RID): Void;
    public function getDebugEnabled(): Bool;
    public function getMaps(): Dynamic;
    public function getProcessInfo(processInfo: Int): Int;
    public function isBakingNavigationMesh(navigationMesh: NavigationMesh): Bool;
    public function linkCreate(): RID;
    public function linkGetEnabled(link: RID): Bool;
    public function linkGetEndPosition(link: RID): Vector3;
    public function linkGetEnterCost(link: RID): Float;
    public function linkGetMap(link: RID): RID;
    public function linkGetNavigationLayers(link: RID): Int;
    public function linkGetOwnerId(link: RID): Int;
    public function linkGetStartPosition(link: RID): Vector3;
    public function linkGetTravelCost(link: RID): Float;
    public function linkIsBidirectional(link: RID): Bool;
    public function linkSetBidirectional(link: RID, bidirectional: Bool): Void;
    public function linkSetEnabled(link: RID, enabled: Bool): Void;
    public function linkSetEndPosition(link: RID, position: GdVector3): Void;
    public function linkSetEnterCost(link: RID, enterCost: Float): Void;
    public function linkSetMap(link: RID, map: RID): Void;
    public function linkSetNavigationLayers(link: RID, navigationLayers: Int): Void;
    public function linkSetOwnerId(link: RID, ownerId: Int): Void;
    public function linkSetStartPosition(link: RID, position: GdVector3): Void;
    public function linkSetTravelCost(link: RID, travelCost: Float): Void;
    public function mapCreate(): RID;
    public function mapForceUpdate(map: RID): Void;
    public function mapGetAgents(map: RID): Dynamic;
    public function mapGetCellHeight(map: RID): Float;
    public function mapGetCellSize(map: RID): Float;
    public function mapGetClosestPoint(map: RID, toPoint: GdVector3): Vector3;
    public function mapGetClosestPointNormal(map: RID, toPoint: GdVector3): Vector3;
    public function mapGetClosestPointOwner(map: RID, toPoint: GdVector3): RID;
    public function mapGetClosestPointToSegment(map: RID, start: GdVector3, end: GdVector3, useCollision: Bool = false): Vector3;
    public function mapGetEdgeConnectionMargin(map: RID): Float;
    public function mapGetIterationId(map: RID): Int;
    public function mapGetLinkConnectionRadius(map: RID): Float;
    public function mapGetLinks(map: RID): Dynamic;
    public function mapGetMergeRasterizerCellScale(map: RID): Float;
    public function mapGetObstacles(map: RID): Dynamic;
    public function mapGetPath(map: RID, origin: GdVector3, destination: GdVector3, optimize: Bool, navigationLayers: Int = 1): PackedVector3Array;
    public function mapGetRandomPoint(map: RID, navigationLayers: Int, uniformly: Bool): Vector3;
    public function mapGetRegions(map: RID): Dynamic;
    public function mapGetUp(map: RID): Vector3;
    public function mapGetUseAsyncIterations(map: RID): Bool;
    public function mapGetUseEdgeConnections(map: RID): Bool;
    public function mapIsActive(map: RID): Bool;
    public function mapSetActive(map: RID, active: Bool): Void;
    public function mapSetCellHeight(map: RID, cellHeight: Float): Void;
    public function mapSetCellSize(map: RID, cellSize: Float): Void;
    public function mapSetEdgeConnectionMargin(map: RID, margin: Float): Void;
    public function mapSetLinkConnectionRadius(map: RID, radius: Float): Void;
    public function mapSetMergeRasterizerCellScale(map: RID, scale: Float): Void;
    public function mapSetUp(map: RID, up: GdVector3): Void;
    public function mapSetUseAsyncIterations(map: RID, enabled: Bool): Void;
    public function mapSetUseEdgeConnections(map: RID, enabled: Bool): Void;
    public function obstacleCreate(): RID;
    public function obstacleGetAvoidanceEnabled(obstacle: RID): Bool;
    public function obstacleGetAvoidanceLayers(obstacle: RID): Int;
    public function obstacleGetHeight(obstacle: RID): Float;
    public function obstacleGetMap(obstacle: RID): RID;
    public function obstacleGetPaused(obstacle: RID): Bool;
    public function obstacleGetPosition(obstacle: RID): Vector3;
    public function obstacleGetRadius(obstacle: RID): Float;
    public function obstacleGetUse3dAvoidance(obstacle: RID): Bool;
    public function obstacleGetVelocity(obstacle: RID): Vector3;
    public function obstacleGetVertices(obstacle: RID): PackedVector3Array;
    public function obstacleSetAvoidanceEnabled(obstacle: RID, enabled: Bool): Void;
    public function obstacleSetAvoidanceLayers(obstacle: RID, layers: Int): Void;
    public function obstacleSetHeight(obstacle: RID, height: Float): Void;
    public function obstacleSetMap(obstacle: RID, map: RID): Void;
    public function obstacleSetPaused(obstacle: RID, paused: Bool): Void;
    public function obstacleSetPosition(obstacle: RID, position: GdVector3): Void;
    public function obstacleSetRadius(obstacle: RID, radius: Float): Void;
    public function obstacleSetUse3dAvoidance(obstacle: RID, enabled: Bool): Void;
    public function obstacleSetVelocity(obstacle: RID, velocity: GdVector3): Void;
    public function obstacleSetVertices(obstacle: RID, vertices: PackedVector3Array): Void;
    public function parseSourceGeometryData(navigationMesh: NavigationMesh, sourceGeometryData: NavigationMeshSourceGeometryData3D, rootNode: Node, ?callback: Callable): Void;
    public function queryPath(parameters: NavigationPathQueryParameters3D, result: NavigationPathQueryResult3D, ?callback: Callable): Void;
    public function regionBakeNavigationMesh(navigationMesh: NavigationMesh, rootNode: Node): Void;
    public function regionCreate(): RID;
    public function regionGetBounds(region: RID): AABB;
    public function regionGetClosestPoint(region: RID, toPoint: GdVector3): Vector3;
    public function regionGetClosestPointNormal(region: RID, toPoint: GdVector3): Vector3;
    public function regionGetClosestPointToSegment(region: RID, start: GdVector3, end: GdVector3, useCollision: Bool = false): Vector3;
    public function regionGetConnectionPathwayEnd(region: RID, connection: Int): Vector3;
    public function regionGetConnectionPathwayStart(region: RID, connection: Int): Vector3;
    public function regionGetConnectionsCount(region: RID): Int;
    public function regionGetEnabled(region: RID): Bool;
    public function regionGetEnterCost(region: RID): Float;
    public function regionGetMap(region: RID): RID;
    public function regionGetNavigationLayers(region: RID): Int;
    public function regionGetOwnerId(region: RID): Int;
    public function regionGetRandomPoint(region: RID, navigationLayers: Int, uniformly: Bool): Vector3;
    public function regionGetTransform(region: RID): Transform3D;
    public function regionGetTravelCost(region: RID): Float;
    public function regionGetUseEdgeConnections(region: RID): Bool;
    public function regionOwnsPoint(region: RID, point: GdVector3): Bool;
    public function regionSetEnabled(region: RID, enabled: Bool): Void;
    public function regionSetEnterCost(region: RID, enterCost: Float): Void;
    public function regionSetMap(region: RID, map: RID): Void;
    public function regionSetNavigationLayers(region: RID, navigationLayers: Int): Void;
    public function regionSetNavigationMesh(region: RID, navigationMesh: NavigationMesh): Void;
    public function regionSetOwnerId(region: RID, ownerId: Int): Void;
    public function regionSetTransform(region: RID, transform: Transform3D): Void;
    public function regionSetTravelCost(region: RID, travelCost: Float): Void;
    public function regionSetUseEdgeConnections(region: RID, enabled: Bool): Void;
    public function setActive(active: Bool): Void;
    public function setDebugEnabled(enabled: Bool): Void;
    public function simplifyPath(path: PackedVector3Array, epsilon: Float): PackedVector3Array;
    public function sourceGeometryParserCreate(): RID;
    public function sourceGeometryParserSetCallback(parser: RID, callback: Callable): Void;
    public var avoidanceDebugChanged: Event;
    public var mapChanged: Event;
    public var navigationDebugChanged: Event;
}
