package sunaba.godot;

import sunaba.core.Event;

@:native("godot.PopupMenu")
extern class PopupMenu extends Popup {
    public var allowSearch: Bool;
    public var hideOnCheckableItemSelection: Bool;
    public var hideOnItemSelection: Bool;
    public var hideOnStateItemSelection: Bool;
    public var itemCount: Int;
    public var preferNativeMenu: Bool;
    public var submenuPopupDelay: Float;
    public var systemMenuId: Int;
    @:native("__new")
    public function new();
    public function activateItemByEvent(event: InputEvent, forGlobalOnly: Bool = false): Bool;
    public function addCheckItem(label: String, id: Int = -1, accel: Int = 0): Void;
    public function addCheckShortcut(shortcut: Shortcut, id: Int = -1, global: Bool = false): Void;
    public function addIconCheckItem(texture: Texture2D, label: String, id: Int = -1, accel: Int = 0): Void;
    public function addIconCheckShortcut(texture: Texture2D, shortcut: Shortcut, id: Int = -1, global: Bool = false): Void;
    public function addIconItem(texture: Texture2D, label: String, id: Int = -1, accel: Int = 0): Void;
    public function addIconRadioCheckItem(texture: Texture2D, label: String, id: Int = -1, accel: Int = 0): Void;
    public function addIconRadioCheckShortcut(texture: Texture2D, shortcut: Shortcut, id: Int = -1, global: Bool = false): Void;
    public function addIconShortcut(texture: Texture2D, shortcut: Shortcut, id: Int = -1, global: Bool = false, allowEcho: Bool = false): Void;
    public function addItem(label: String, id: Int = -1, accel: Int = 0): Void;
    public function addMultistateItem(label: String, maxStates: Int, defaultState: Int = 0, id: Int = -1, accel: Int = 0): Void;
    public function addRadioCheckItem(label: String, id: Int = -1, accel: Int = 0): Void;
    public function addRadioCheckShortcut(shortcut: Shortcut, id: Int = -1, global: Bool = false): Void;
    public function addSeparator(?label: String, id: Int = -1): Void;
    public function addShortcut(shortcut: Shortcut, id: Int = -1, global: Bool = false, allowEcho: Bool = false): Void;
    public function addSubmenuItem(label: String, submenu: String, id: Int = -1): Void;
    public function addSubmenuNodeItem(label: String, submenu: PopupMenu, id: Int = -1): Void;
    public function clear(freeSubmenus: Bool = false): Void;
    public function getFocusedItem(): Int;
    public function getItemAccelerator(index: Int): Int;
    public function getItemIcon(index: Int): Texture2D;
    public function getItemIconMaxWidth(index: Int): Int;
    public function getItemIconModulate(index: Int): Color;
    public function getItemId(index: Int): Int;
    public function getItemIndent(index: Int): Int;
    public function getItemIndex(id: Int): Int;
    public function getItemLanguage(index: Int): String;
    public function getItemMetadata(index: Int): Variant;
    public function getItemMultistate(index: Int): Int;
    public function getItemMultistateMax(index: Int): Int;
    public function getItemShortcut(index: Int): Shortcut;
    public function getItemSubmenu(index: Int): String;
    public function getItemSubmenuNode(index: Int): PopupMenu;
    public function getItemText(index: Int): String;
    public function getItemTextDirection(index: Int): Int;
    public function getItemTooltip(index: Int): String;
    public function isItemCheckable(index: Int): Bool;
    public function isItemChecked(index: Int): Bool;
    public function isItemDisabled(index: Int): Bool;
    public function isItemRadioCheckable(index: Int): Bool;
    public function isItemSeparator(index: Int): Bool;
    public function isItemShortcutDisabled(index: Int): Bool;
    public function isNativeMenu(): Bool;
    public function isSystemMenu(): Bool;
    public function removeItem(index: Int): Void;
    public function scrollToItem(index: Int): Void;
    public function setFocusedItem(index: Int): Void;
    public function setItemAccelerator(index: Int, accel: Int): Void;
    public function setItemAsCheckable(index: Int, enable: Bool): Void;
    public function setItemAsRadioCheckable(index: Int, enable: Bool): Void;
    public function setItemAsSeparator(index: Int, enable: Bool): Void;
    public function setItemChecked(index: Int, checked: Bool): Void;
    public function setItemDisabled(index: Int, disabled: Bool): Void;
    public function setItemIcon(index: Int, icon: Texture2D): Void;
    public function setItemIconMaxWidth(index: Int, width: Int): Void;
    public function setItemIconModulate(index: Int, modulate: Color): Void;
    public function setItemId(index: Int, id: Int): Void;
    public function setItemIndent(index: Int, indent: Int): Void;
    public function setItemLanguage(index: Int, language: String): Void;
    public function setItemMetadata(index: Int, metadata: Variant): Void;
    public function setItemMultistate(index: Int, state: Int): Void;
    public function setItemMultistateMax(index: Int, maxStates: Int): Void;
    public function setItemShortcut(index: Int, shortcut: Shortcut, global: Bool = false): Void;
    public function setItemShortcutDisabled(index: Int, disabled: Bool): Void;
    public function setItemSubmenu(index: Int, submenu: String): Void;
    public function setItemSubmenuNode(index: Int, submenu: PopupMenu): Void;
    public function setItemText(index: Int, text: String): Void;
    public function setItemTextDirection(index: Int, direction: Int): Void;
    public function setItemTooltip(index: Int, tooltip: String): Void;
    public function toggleItemChecked(index: Int): Void;
    public function toggleItemMultistate(index: Int): Void;
    public var idFocused: Event;
    public var idPressed: Event;
    public var indexPressed: Event;
    public var menuChanged: Event;
}
