package sunaba.godot;

import sunaba.core.Event;

@:native("godot.ProjectSettings")
extern class ProjectSettings extends Object {
    public var animationWarningsCheckAngleInterpolationTypeConflicting: Bool;
    public var animationWarningsCheckInvalidTrackPaths: Bool;
    public var applicationBootSplashBgColor: Color;
    public var applicationBootSplashFullsize: Bool;
    public var applicationBootSplashImage: String;
    public var applicationBootSplashMinimumDisplayTime: Int;
    public var applicationBootSplashShowImage: Bool;
    public var applicationBootSplashUseFilter: Bool;
    public var applicationConfigAutoAcceptQuit: Bool;
    public var applicationConfigCustomUserDirName: String;
    public var applicationConfigDescription: String;
    public var applicationConfigIcon: String;
    public var applicationConfigMacosNativeIcon: String;
    public var applicationConfigName: String;
    public var applicationConfigNameLocalized: Map<Dynamic, Dynamic>;
    public var applicationConfigProjectSettingsOverride: String;
    public var applicationConfigQuitOnGoBack: Bool;
    public var applicationConfigUseCustomUserDir: Bool;
    public var applicationConfigUseHiddenProjectDataDirectory: Bool;
    public var applicationConfigVersion: String;
    public var applicationConfigWindowsNativeIcon: String;
    public var applicationRunDeltaSmoothing: Bool;
    public var applicationRunDisableStderr: Bool;
    public var applicationRunDisableStdout: Bool;
    public var applicationRunEnableAltSpaceMenu: Bool;
    public var applicationRunFlushStdoutOnPrint: Bool;
    public var applicationRunFlushStdoutOnPrint.debug: Bool;
    public var applicationRunFrameDelayMsec: Int;
    public var applicationRunLowProcessorMode: Bool;
    public var applicationRunLowProcessorModeSleepUsec: Int;
    public var applicationRunMainLoopType: String;
    public var applicationRunMainScene: String;
    public var applicationRunMaxFps: Int;
    public var applicationRunPrintHeader: Bool;
    public var audioBusesChannelDisableThresholdDb: Float;
    public var audioBusesChannelDisableTime: Float;
    public var audioBusesDefaultBusLayout: String;
    public var audioDriverDriver: String;
    public var audioDriverEnableInput: Bool;
    public var audioDriverMixRate: Int;
    public var audioDriverMixRate.web: Int;
    public var audioDriverOutputLatency: Int;
    public var audioDriverOutputLatency.web: Int;
    public var audioGeneral2dPanningStrength: Float;
    public var audioGeneral3dPanningStrength: Float;
    public var audioGeneralDefaultPlaybackType: Int;
    public var audioGeneralDefaultPlaybackType.web: Int;
    public var audioGeneralIosMixWithOthers: Bool;
    public var audioGeneralIosSessionCategory: Int;
    public var audioGeneralTextToSpeech: Bool;
    public var audioVideoVideoDelayCompensationMs: Int;
    public var colladaUseAmbient: Bool;
    public var compressionFormatsGzipCompressionLevel: Int;
    public var compressionFormatsZlibCompressionLevel: Int;
    public var compressionFormatsZstdCompressionLevel: Int;
    public var compressionFormatsZstdLongDistanceMatching: Bool;
    public var compressionFormatsZstdWindowLogSize: Int;
    public var debugCanvasItemsDebugRedrawColor: Color;
    public var debugCanvasItemsDebugRedrawTime: Float;
    public var debugFileLoggingEnableFileLogging: Bool;
    public var debugFileLoggingEnableFileLogging.pc: Bool;
    public var debugFileLoggingLogPath: String;
    public var debugFileLoggingMaxLogFiles: Int;
    public var debugGdscriptWarningsAssertAlwaysFalse: Int;
    public var debugGdscriptWarningsAssertAlwaysTrue: Int;
    public var debugGdscriptWarningsConfusableCaptureReassignment: Int;
    public var debugGdscriptWarningsConfusableIdentifier: Int;
    public var debugGdscriptWarningsConfusableLocalDeclaration: Int;
    public var debugGdscriptWarningsConfusableLocalUsage: Int;
    public var debugGdscriptWarningsConstantUsedAsFunction: Int;
    public var debugGdscriptWarningsDeprecatedKeyword: Int;
    public var debugGdscriptWarningsEmptyFile: Int;
    public var debugGdscriptWarningsEnable: Bool;
    public var debugGdscriptWarningsEnumVariableWithoutDefault: Int;
    public var debugGdscriptWarningsExcludeAddons: Bool;
    public var debugGdscriptWarningsFunctionUsedAsProperty: Int;
    public var debugGdscriptWarningsGetNodeDefaultWithoutOnready: Int;
    public var debugGdscriptWarningsIncompatibleTernary: Int;
    public var debugGdscriptWarningsInferenceOnVariant: Int;
    public var debugGdscriptWarningsInferredDeclaration: Int;
    public var debugGdscriptWarningsIntAsEnumWithoutCast: Int;
    public var debugGdscriptWarningsIntAsEnumWithoutMatch: Int;
    public var debugGdscriptWarningsIntegerDivision: Int;
    public var debugGdscriptWarningsMissingTool: Int;
    public var debugGdscriptWarningsNarrowingConversion: Int;
    public var debugGdscriptWarningsNativeMethodOverride: Int;
    public var debugGdscriptWarningsOnreadyWithExport: Int;
    public var debugGdscriptWarningsPropertyUsedAsFunction: Int;
    public var debugGdscriptWarningsRedundantAwait: Int;
    public var debugGdscriptWarningsRedundantStaticUnload: Int;
    public var debugGdscriptWarningsRenamedInGodot4Hint: Bool;
    public var debugGdscriptWarningsReturnValueDiscarded: Int;
    public var debugGdscriptWarningsShadowedGlobalIdentifier: Int;
    public var debugGdscriptWarningsShadowedVariable: Int;
    public var debugGdscriptWarningsShadowedVariableBaseClass: Int;
    public var debugGdscriptWarningsStandaloneExpression: Int;
    public var debugGdscriptWarningsStandaloneTernary: Int;
    public var debugGdscriptWarningsStaticCalledOnInstance: Int;
    public var debugGdscriptWarningsUnassignedVariable: Int;
    public var debugGdscriptWarningsUnassignedVariableOpAssign: Int;
    public var debugGdscriptWarningsUnreachableCode: Int;
    public var debugGdscriptWarningsUnreachablePattern: Int;
    public var debugGdscriptWarningsUnsafeCallArgument: Int;
    public var debugGdscriptWarningsUnsafeCast: Int;
    public var debugGdscriptWarningsUnsafeMethodAccess: Int;
    public var debugGdscriptWarningsUnsafePropertyAccess: Int;
    public var debugGdscriptWarningsUnsafeVoidReturn: Int;
    public var debugGdscriptWarningsUntypedDeclaration: Int;
    public var debugGdscriptWarningsUnusedLocalConstant: Int;
    public var debugGdscriptWarningsUnusedParameter: Int;
    public var debugGdscriptWarningsUnusedPrivateClassVariable: Int;
    public var debugGdscriptWarningsUnusedSignal: Int;
    public var debugGdscriptWarningsUnusedVariable: Int;
    public var debugSettingsCrashHandlerMessage: String;
    public var debugSettingsCrashHandlerMessage.editor: String;
    public var debugSettingsGdscriptMaxCallStack: Int;
    public var debugSettingsPhysicsInterpolationEnableWarnings: Bool;
    public var debugSettingsProfilerMaxFunctions: Int;
    public var debugSettingsProfilerMaxTimestampQueryElements: Int;
    public var debugSettingsStdoutPrintFps: Bool;
    public var debugSettingsStdoutPrintGpuProfile: Bool;
    public var debugSettingsStdoutVerboseStdout: Bool;
    public var debugShaderLanguageWarningsDeviceLimitExceeded: Bool;
    public var debugShaderLanguageWarningsEnable: Bool;
    public var debugShaderLanguageWarningsFloatComparison: Bool;
    public var debugShaderLanguageWarningsFormattingError: Bool;
    public var debugShaderLanguageWarningsMagicPositionWrite: Bool;
    public var debugShaderLanguageWarningsTreatWarningsAsErrors: Bool;
    public var debugShaderLanguageWarningsUnusedConstant: Bool;
    public var debugShaderLanguageWarningsUnusedFunction: Bool;
    public var debugShaderLanguageWarningsUnusedLocalVariable: Bool;
    public var debugShaderLanguageWarningsUnusedStruct: Bool;
    public var debugShaderLanguageWarningsUnusedUniform: Bool;
    public var debugShaderLanguageWarningsUnusedVarying: Bool;
    public var debugShapesAvoidanceAgentsRadiusColor: Color;
    public var debugShapesAvoidanceEnableAgentsRadius: Bool;
    public var debugShapesAvoidanceEnableObstaclesRadius: Bool;
    public var debugShapesAvoidanceEnableObstaclesStatic: Bool;
    public var debugShapesAvoidanceObstaclesRadiusColor: Color;
    public var debugShapesAvoidanceObstaclesStaticEdgePushinColor: Color;
    public var debugShapesAvoidanceObstaclesStaticEdgePushoutColor: Color;
    public var debugShapesAvoidanceObstaclesStaticFacePushinColor: Color;
    public var debugShapesAvoidanceObstaclesStaticFacePushoutColor: Color;
    public var debugShapesCollisionContactColor: Color;
    public var debugShapesCollisionDraw2dOutlines: Bool;
    public var debugShapesCollisionMaxContactsDisplayed: Int;
    public var debugShapesCollisionShapeColor: Color;
    public var debugShapesNavigationAgentPathColor: Color;
    public var debugShapesNavigationAgentPathPointSize: Float;
    public var debugShapesNavigationEdgeConnectionColor: Color;
    public var debugShapesNavigationEnableAgentPaths: Bool;
    public var debugShapesNavigationEnableAgentPathsXray: Bool;
    public var debugShapesNavigationEnableEdgeConnections: Bool;
    public var debugShapesNavigationEnableEdgeConnectionsXray: Bool;
    public var debugShapesNavigationEnableEdgeLines: Bool;
    public var debugShapesNavigationEnableEdgeLinesXray: Bool;
    public var debugShapesNavigationEnableGeometryFaceRandomColor: Bool;
    public var debugShapesNavigationEnableLinkConnections: Bool;
    public var debugShapesNavigationEnableLinkConnectionsXray: Bool;
    public var debugShapesNavigationGeometryEdgeColor: Color;
    public var debugShapesNavigationGeometryEdgeDisabledColor: Color;
    public var debugShapesNavigationGeometryFaceColor: Color;
    public var debugShapesNavigationGeometryFaceDisabledColor: Color;
    public var debugShapesNavigationLinkConnectionColor: Color;
    public var debugShapesNavigationLinkConnectionDisabledColor: Color;
    public var debugShapesPathsGeometryColor: Color;
    public var debugShapesPathsGeometryWidth: Float;
    public var displayDisplayServerDriver: String;
    public var displayDisplayServerDriver.android: String;
    public var displayDisplayServerDriver.ios: String;
    public var displayDisplayServerDriver.linuxbsd: String;
    public var displayDisplayServerDriver.macos: String;
    public var displayDisplayServerDriver.windows: String;
    public var displayMouseCursorCustomImage: String;
    public var displayMouseCursorCustomImageHotspot: Vector2;
    public var displayMouseCursorTooltipPositionOffset: Vector2;
    public var displayWindowDpiAllowHidpi: Bool;
    public var displayWindowEnergySavingKeepScreenOn: Bool;
    public var displayWindowFramePacingAndroidEnableFramePacing: Bool;
    public var displayWindowFramePacingAndroidSwappyMode: Int;
    public var displayWindowHandheldOrientation: Int;
    public var displayWindowIosAllowHighRefreshRate: Bool;
    public var displayWindowIosHideHomeIndicator: Bool;
    public var displayWindowIosHideStatusBar: Bool;
    public var displayWindowIosSuppressUiGesture: Bool;
    public var displayWindowPerPixelTransparencyAllowed: Bool;
    public var displayWindowSizeAlwaysOnTop: Bool;
    public var displayWindowSizeBorderless: Bool;
    public var displayWindowSizeExtendToTitle: Bool;
    public var displayWindowSizeInitialPosition: Vector2i;
    public var displayWindowSizeInitialPositionType: Int;
    public var displayWindowSizeInitialScreen: Int;
    public var displayWindowSizeMode: Int;
    public var displayWindowSizeNoFocus: Bool;
    public var displayWindowSizeResizable: Bool;
    public var displayWindowSizeSharpCorners: Bool;
    public var displayWindowSizeTransparent: Bool;
    public var displayWindowSizeViewportHeight: Int;
    public var displayWindowSizeViewportWidth: Int;
    public var displayWindowSizeWindowHeightOverride: Int;
    public var displayWindowSizeWindowWidthOverride: Int;
    public var displayWindowStretchAspect: String;
    public var displayWindowStretchMode: String;
    public var displayWindowStretchScale: Float;
    public var displayWindowStretchScaleMode: String;
    public var displayWindowSubwindowsEmbedSubwindows: Bool;
    public var displayWindowVsyncVsyncMode: Int;
    public var dotnetProjectAssemblyName: String;
    public var dotnetProjectAssemblyReloadAttempts: Int;
    public var dotnetProjectSolutionDirectory: String;
    public var editorExportConvertTextResourcesToBinary: Bool;
    public var editorImportAtlasMaxWidth: Int;
    public var editorImportReimportMissingImportedFiles: Bool;
    public var editorImportUseMultipleThreads: Bool;
    public var editorMovieWriterDisableVsync: Bool;
    public var editorMovieWriterFps: Int;
    public var editorMovieWriterMixRate: Int;
    public var editorMovieWriterMjpegQuality: Float;
    public var editorMovieWriterMovieFile: String;
    public var editorMovieWriterSpeakerMode: Int;
    public var editorNamingDefaultSignalCallbackName: String;
    public var editorNamingDefaultSignalCallbackToSelfName: String;
    public var editorNamingNodeNameCasing: Int;
    public var editorNamingNodeNameNumSeparator: Int;
    public var editorNamingSceneNameCasing: Int;
    public var editorNamingScriptNameCasing: Int;
    public var editorRunMainRunArgs: String;
    public var editorScriptSearchInFileExtensions: PackedStringArray;
    public var editorScriptTemplatesSearchPath: String;
    public var editorVersionControlAutoloadOnStartup: Bool;
    public var editorVersionControlPluginName: String;
    public var filesystemImportBlenderEnabled: Bool;
    public var filesystemImportBlenderEnabled.android: Bool;
    public var filesystemImportBlenderEnabled.web: Bool;
    public var filesystemImportFbx2gltfEnabled: Bool;
    public var filesystemImportFbx2gltfEnabled.android: Bool;
    public var filesystemImportFbx2gltfEnabled.web: Bool;
    public var guiCommonDefaultScrollDeadzone: Int;
    public var guiCommonSnapControlsToPixels: Bool;
    public var guiCommonSwapCancelOk: Bool;
    public var guiCommonTextEditUndoStackMaxSize: Int;
    public var guiFontsDynamicFontsUseOversampling: Bool;
    public var guiThemeCustom: String;
    public var guiThemeCustomFont: String;
    public var guiThemeDefaultFontAntialiasing: Int;
    public var guiThemeDefaultFontGenerateMipmaps: Bool;
    public var guiThemeDefaultFontHinting: Int;
    public var guiThemeDefaultFontMultichannelSignedDistanceField: Bool;
    public var guiThemeDefaultFontSubpixelPositioning: Int;
    public var guiThemeDefaultThemeScale: Float;
    public var guiThemeLcdSubpixelLayout: Int;
    public var guiTimersButtonShortcutFeedbackHighlightTime: Float;
    public var guiTimersIncrementalSearchMaxIntervalMsec: Int;
    public var guiTimersTextEditIdleDetectSec: Float;
    public var guiTimersTooltipDelaySec: Float;
    public var guiTimersTooltipDelaySec.editorHint: Float;
    public var inputUiAccept: Map<Dynamic, Dynamic>;
    public var inputUiCancel: Map<Dynamic, Dynamic>;
    public var inputUiCopy: Map<Dynamic, Dynamic>;
    public var inputUiCut: Map<Dynamic, Dynamic>;
    public var inputUiDown: Map<Dynamic, Dynamic>;
    public var inputUiEnd: Map<Dynamic, Dynamic>;
    public var inputUiFiledialogRefresh: Map<Dynamic, Dynamic>;
    public var inputUiFiledialogShowHidden: Map<Dynamic, Dynamic>;
    public var inputUiFiledialogUpOneLevel: Map<Dynamic, Dynamic>;
    public var inputUiFocusNext: Map<Dynamic, Dynamic>;
    public var inputUiFocusPrev: Map<Dynamic, Dynamic>;
    public var inputUiGraphDelete: Map<Dynamic, Dynamic>;
    public var inputUiGraphDuplicate: Map<Dynamic, Dynamic>;
    public var inputUiHome: Map<Dynamic, Dynamic>;
    public var inputUiLeft: Map<Dynamic, Dynamic>;
    public var inputUiMenu: Map<Dynamic, Dynamic>;
    public var inputUiPageDown: Map<Dynamic, Dynamic>;
    public var inputUiPageUp: Map<Dynamic, Dynamic>;
    public var inputUiPaste: Map<Dynamic, Dynamic>;
    public var inputUiRedo: Map<Dynamic, Dynamic>;
    public var inputUiRight: Map<Dynamic, Dynamic>;
    public var inputUiSelect: Map<Dynamic, Dynamic>;
    public var inputUiSwapInputDirection: Map<Dynamic, Dynamic>;
    public var inputUiTextAddSelectionForNextOccurrence: Map<Dynamic, Dynamic>;
    public var inputUiTextBackspace: Map<Dynamic, Dynamic>;
    public var inputUiTextBackspaceAllToLeft: Map<Dynamic, Dynamic>;
    public var inputUiTextBackspaceAllToLeft.macos: Map<Dynamic, Dynamic>;
    public var inputUiTextBackspaceWord: Map<Dynamic, Dynamic>;
    public var inputUiTextBackspaceWord.macos: Map<Dynamic, Dynamic>;
    public var inputUiTextCaretAddAbove: Map<Dynamic, Dynamic>;
    public var inputUiTextCaretAddAbove.macos: Map<Dynamic, Dynamic>;
    public var inputUiTextCaretAddBelow: Map<Dynamic, Dynamic>;
    public var inputUiTextCaretAddBelow.macos: Map<Dynamic, Dynamic>;
    public var inputUiTextCaretDocumentEnd: Map<Dynamic, Dynamic>;
    public var inputUiTextCaretDocumentEnd.macos: Map<Dynamic, Dynamic>;
    public var inputUiTextCaretDocumentStart: Map<Dynamic, Dynamic>;
    public var inputUiTextCaretDocumentStart.macos: Map<Dynamic, Dynamic>;
    public var inputUiTextCaretDown: Map<Dynamic, Dynamic>;
    public var inputUiTextCaretLeft: Map<Dynamic, Dynamic>;
    public var inputUiTextCaretLineEnd: Map<Dynamic, Dynamic>;
    public var inputUiTextCaretLineEnd.macos: Map<Dynamic, Dynamic>;
    public var inputUiTextCaretLineStart: Map<Dynamic, Dynamic>;
    public var inputUiTextCaretLineStart.macos: Map<Dynamic, Dynamic>;
    public var inputUiTextCaretPageDown: Map<Dynamic, Dynamic>;
    public var inputUiTextCaretPageUp: Map<Dynamic, Dynamic>;
    public var inputUiTextCaretRight: Map<Dynamic, Dynamic>;
    public var inputUiTextCaretUp: Map<Dynamic, Dynamic>;
    public var inputUiTextCaretWordLeft: Map<Dynamic, Dynamic>;
    public var inputUiTextCaretWordLeft.macos: Map<Dynamic, Dynamic>;
    public var inputUiTextCaretWordRight: Map<Dynamic, Dynamic>;
    public var inputUiTextCaretWordRight.macos: Map<Dynamic, Dynamic>;
    public var inputUiTextClearCaretsAndSelection: Map<Dynamic, Dynamic>;
    public var inputUiTextCompletionAccept: Map<Dynamic, Dynamic>;
    public var inputUiTextCompletionQuery: Map<Dynamic, Dynamic>;
    public var inputUiTextCompletionReplace: Map<Dynamic, Dynamic>;
    public var inputUiTextDedent: Map<Dynamic, Dynamic>;
    public var inputUiTextDelete: Map<Dynamic, Dynamic>;
    public var inputUiTextDeleteAllToRight: Map<Dynamic, Dynamic>;
    public var inputUiTextDeleteAllToRight.macos: Map<Dynamic, Dynamic>;
    public var inputUiTextDeleteWord: Map<Dynamic, Dynamic>;
    public var inputUiTextDeleteWord.macos: Map<Dynamic, Dynamic>;
    public var inputUiTextIndent: Map<Dynamic, Dynamic>;
    public var inputUiTextNewline: Map<Dynamic, Dynamic>;
    public var inputUiTextNewlineAbove: Map<Dynamic, Dynamic>;
    public var inputUiTextNewlineBlank: Map<Dynamic, Dynamic>;
    public var inputUiTextScrollDown: Map<Dynamic, Dynamic>;
    public var inputUiTextScrollDown.macos: Map<Dynamic, Dynamic>;
    public var inputUiTextScrollUp: Map<Dynamic, Dynamic>;
    public var inputUiTextScrollUp.macos: Map<Dynamic, Dynamic>;
    public var inputUiTextSelectAll: Map<Dynamic, Dynamic>;
    public var inputUiTextSelectWordUnderCaret: Map<Dynamic, Dynamic>;
    public var inputUiTextSelectWordUnderCaret.macos: Map<Dynamic, Dynamic>;
    public var inputUiTextSkipSelectionForNextOccurrence: Map<Dynamic, Dynamic>;
    public var inputUiTextSubmit: Map<Dynamic, Dynamic>;
    public var inputUiTextToggleInsertMode: Map<Dynamic, Dynamic>;
    public var inputUiUndo: Map<Dynamic, Dynamic>;
    public var inputUiUnicodeStart: Map<Dynamic, Dynamic>;
    public var inputUiUp: Map<Dynamic, Dynamic>;
    public var inputDevicesBufferingAgileEventFlushing: Bool;
    public var inputDevicesCompatibilityLegacyJustPressedBehavior: Bool;
    public var inputDevicesPenTabletDriver: String;
    public var inputDevicesPenTabletDriver.windows: String;
    public var inputDevicesPointingAndroidEnableLongPressAsRightClick: Bool;
    public var inputDevicesPointingAndroidEnablePanAndScaleGestures: Bool;
    public var inputDevicesPointingAndroidRotaryInputScrollAxis: Int;
    public var inputDevicesPointingEmulateMouseFromTouch: Bool;
    public var inputDevicesPointingEmulateTouchFromMouse: Bool;
    public var inputDevicesSensorsEnableAccelerometer: Bool;
    public var inputDevicesSensorsEnableGravity: Bool;
    public var inputDevicesSensorsEnableGyroscope: Bool;
    public var inputDevicesSensorsEnableMagnetometer: Bool;
    public var internationalizationLocaleFallback: String;
    public var internationalizationLocaleIncludeTextServerData: Bool;
    public var internationalizationLocaleTest: String;
    public var internationalizationPseudolocalizationDoubleVowels: Bool;
    public var internationalizationPseudolocalizationExpansionRatio: Float;
    public var internationalizationPseudolocalizationFakeBidi: Bool;
    public var internationalizationPseudolocalizationOverride: Bool;
    public var internationalizationPseudolocalizationPrefix: String;
    public var internationalizationPseudolocalizationReplaceWithAccents: Bool;
    public var internationalizationPseudolocalizationSkipPlaceholders: Bool;
    public var internationalizationPseudolocalizationSuffix: String;
    public var internationalizationPseudolocalizationUsePseudolocalization: Bool;
    public var internationalizationRenderingForceRightToLeftLayoutDirection: Bool;
    public var internationalizationRenderingRootNodeAutoTranslate: Bool;
    public var internationalizationRenderingRootNodeLayoutDirection: Int;
    public var internationalizationRenderingTextDriver: String;
    public var layerNames2dNavigationLayer1: String;
    public var layerNames2dNavigationLayer2: String;
    public var layerNames2dNavigationLayer3: String;
    public var layerNames2dNavigationLayer4: String;
    public var layerNames2dNavigationLayer5: String;
    public var layerNames2dNavigationLayer6: String;
    public var layerNames2dNavigationLayer7: String;
    public var layerNames2dNavigationLayer8: String;
    public var layerNames2dNavigationLayer9: String;
    public var layerNames2dNavigationLayer10: String;
    public var layerNames2dNavigationLayer11: String;
    public var layerNames2dNavigationLayer12: String;
    public var layerNames2dNavigationLayer13: String;
    public var layerNames2dNavigationLayer14: String;
    public var layerNames2dNavigationLayer15: String;
    public var layerNames2dNavigationLayer16: String;
    public var layerNames2dNavigationLayer17: String;
    public var layerNames2dNavigationLayer18: String;
    public var layerNames2dNavigationLayer19: String;
    public var layerNames2dNavigationLayer20: String;
    public var layerNames2dNavigationLayer21: String;
    public var layerNames2dNavigationLayer22: String;
    public var layerNames2dNavigationLayer23: String;
    public var layerNames2dNavigationLayer24: String;
    public var layerNames2dNavigationLayer25: String;
    public var layerNames2dNavigationLayer26: String;
    public var layerNames2dNavigationLayer27: String;
    public var layerNames2dNavigationLayer28: String;
    public var layerNames2dNavigationLayer29: String;
    public var layerNames2dNavigationLayer30: String;
    public var layerNames2dNavigationLayer31: String;
    public var layerNames2dNavigationLayer32: String;
    public var layerNames2dPhysicsLayer1: String;
    public var layerNames2dPhysicsLayer2: String;
    public var layerNames2dPhysicsLayer3: String;
    public var layerNames2dPhysicsLayer4: String;
    public var layerNames2dPhysicsLayer5: String;
    public var layerNames2dPhysicsLayer6: String;
    public var layerNames2dPhysicsLayer7: String;
    public var layerNames2dPhysicsLayer8: String;
    public var layerNames2dPhysicsLayer9: String;
    public var layerNames2dPhysicsLayer10: String;
    public var layerNames2dPhysicsLayer11: String;
    public var layerNames2dPhysicsLayer12: String;
    public var layerNames2dPhysicsLayer13: String;
    public var layerNames2dPhysicsLayer14: String;
    public var layerNames2dPhysicsLayer15: String;
    public var layerNames2dPhysicsLayer16: String;
    public var layerNames2dPhysicsLayer17: String;
    public var layerNames2dPhysicsLayer18: String;
    public var layerNames2dPhysicsLayer19: String;
    public var layerNames2dPhysicsLayer20: String;
    public var layerNames2dPhysicsLayer21: String;
    public var layerNames2dPhysicsLayer22: String;
    public var layerNames2dPhysicsLayer23: String;
    public var layerNames2dPhysicsLayer24: String;
    public var layerNames2dPhysicsLayer25: String;
    public var layerNames2dPhysicsLayer26: String;
    public var layerNames2dPhysicsLayer27: String;
    public var layerNames2dPhysicsLayer28: String;
    public var layerNames2dPhysicsLayer29: String;
    public var layerNames2dPhysicsLayer30: String;
    public var layerNames2dPhysicsLayer31: String;
    public var layerNames2dPhysicsLayer32: String;
    public var layerNames2dRenderLayer1: String;
    public var layerNames2dRenderLayer2: String;
    public var layerNames2dRenderLayer3: String;
    public var layerNames2dRenderLayer4: String;
    public var layerNames2dRenderLayer5: String;
    public var layerNames2dRenderLayer6: String;
    public var layerNames2dRenderLayer7: String;
    public var layerNames2dRenderLayer8: String;
    public var layerNames2dRenderLayer9: String;
    public var layerNames2dRenderLayer10: String;
    public var layerNames2dRenderLayer11: String;
    public var layerNames2dRenderLayer12: String;
    public var layerNames2dRenderLayer13: String;
    public var layerNames2dRenderLayer14: String;
    public var layerNames2dRenderLayer15: String;
    public var layerNames2dRenderLayer16: String;
    public var layerNames2dRenderLayer17: String;
    public var layerNames2dRenderLayer18: String;
    public var layerNames2dRenderLayer19: String;
    public var layerNames2dRenderLayer20: String;
    public var layerNames3dNavigationLayer1: String;
    public var layerNames3dNavigationLayer2: String;
    public var layerNames3dNavigationLayer3: String;
    public var layerNames3dNavigationLayer4: String;
    public var layerNames3dNavigationLayer5: String;
    public var layerNames3dNavigationLayer6: String;
    public var layerNames3dNavigationLayer7: String;
    public var layerNames3dNavigationLayer8: String;
    public var layerNames3dNavigationLayer9: String;
    public var layerNames3dNavigationLayer10: String;
    public var layerNames3dNavigationLayer11: String;
    public var layerNames3dNavigationLayer12: String;
    public var layerNames3dNavigationLayer13: String;
    public var layerNames3dNavigationLayer14: String;
    public var layerNames3dNavigationLayer15: String;
    public var layerNames3dNavigationLayer16: String;
    public var layerNames3dNavigationLayer17: String;
    public var layerNames3dNavigationLayer18: String;
    public var layerNames3dNavigationLayer19: String;
    public var layerNames3dNavigationLayer20: String;
    public var layerNames3dNavigationLayer21: String;
    public var layerNames3dNavigationLayer22: String;
    public var layerNames3dNavigationLayer23: String;
    public var layerNames3dNavigationLayer24: String;
    public var layerNames3dNavigationLayer25: String;
    public var layerNames3dNavigationLayer26: String;
    public var layerNames3dNavigationLayer27: String;
    public var layerNames3dNavigationLayer28: String;
    public var layerNames3dNavigationLayer29: String;
    public var layerNames3dNavigationLayer30: String;
    public var layerNames3dNavigationLayer31: String;
    public var layerNames3dNavigationLayer32: String;
    public var layerNames3dPhysicsLayer1: String;
    public var layerNames3dPhysicsLayer2: String;
    public var layerNames3dPhysicsLayer3: String;
    public var layerNames3dPhysicsLayer4: String;
    public var layerNames3dPhysicsLayer5: String;
    public var layerNames3dPhysicsLayer6: String;
    public var layerNames3dPhysicsLayer7: String;
    public var layerNames3dPhysicsLayer8: String;
    public var layerNames3dPhysicsLayer9: String;
    public var layerNames3dPhysicsLayer10: String;
    public var layerNames3dPhysicsLayer11: String;
    public var layerNames3dPhysicsLayer12: String;
    public var layerNames3dPhysicsLayer13: String;
    public var layerNames3dPhysicsLayer14: String;
    public var layerNames3dPhysicsLayer15: String;
    public var layerNames3dPhysicsLayer16: String;
    public var layerNames3dPhysicsLayer17: String;
    public var layerNames3dPhysicsLayer18: String;
    public var layerNames3dPhysicsLayer19: String;
    public var layerNames3dPhysicsLayer20: String;
    public var layerNames3dPhysicsLayer21: String;
    public var layerNames3dPhysicsLayer22: String;
    public var layerNames3dPhysicsLayer23: String;
    public var layerNames3dPhysicsLayer24: String;
    public var layerNames3dPhysicsLayer25: String;
    public var layerNames3dPhysicsLayer26: String;
    public var layerNames3dPhysicsLayer27: String;
    public var layerNames3dPhysicsLayer28: String;
    public var layerNames3dPhysicsLayer29: String;
    public var layerNames3dPhysicsLayer30: String;
    public var layerNames3dPhysicsLayer31: String;
    public var layerNames3dPhysicsLayer32: String;
    public var layerNames3dRenderLayer1: String;
    public var layerNames3dRenderLayer2: String;
    public var layerNames3dRenderLayer3: String;
    public var layerNames3dRenderLayer4: String;
    public var layerNames3dRenderLayer5: String;
    public var layerNames3dRenderLayer6: String;
    public var layerNames3dRenderLayer7: String;
    public var layerNames3dRenderLayer8: String;
    public var layerNames3dRenderLayer9: String;
    public var layerNames3dRenderLayer10: String;
    public var layerNames3dRenderLayer11: String;
    public var layerNames3dRenderLayer12: String;
    public var layerNames3dRenderLayer13: String;
    public var layerNames3dRenderLayer14: String;
    public var layerNames3dRenderLayer15: String;
    public var layerNames3dRenderLayer16: String;
    public var layerNames3dRenderLayer17: String;
    public var layerNames3dRenderLayer18: String;
    public var layerNames3dRenderLayer19: String;
    public var layerNames3dRenderLayer20: String;
    public var layerNamesAvoidanceLayer1: String;
    public var layerNamesAvoidanceLayer2: String;
    public var layerNamesAvoidanceLayer3: String;
    public var layerNamesAvoidanceLayer4: String;
    public var layerNamesAvoidanceLayer5: String;
    public var layerNamesAvoidanceLayer6: String;
    public var layerNamesAvoidanceLayer7: String;
    public var layerNamesAvoidanceLayer8: String;
    public var layerNamesAvoidanceLayer9: String;
    public var layerNamesAvoidanceLayer10: String;
    public var layerNamesAvoidanceLayer11: String;
    public var layerNamesAvoidanceLayer12: String;
    public var layerNamesAvoidanceLayer13: String;
    public var layerNamesAvoidanceLayer14: String;
    public var layerNamesAvoidanceLayer15: String;
    public var layerNamesAvoidanceLayer16: String;
    public var layerNamesAvoidanceLayer17: String;
    public var layerNamesAvoidanceLayer18: String;
    public var layerNamesAvoidanceLayer19: String;
    public var layerNamesAvoidanceLayer20: String;
    public var layerNamesAvoidanceLayer21: String;
    public var layerNamesAvoidanceLayer22: String;
    public var layerNamesAvoidanceLayer23: String;
    public var layerNamesAvoidanceLayer24: String;
    public var layerNamesAvoidanceLayer25: String;
    public var layerNamesAvoidanceLayer26: String;
    public var layerNamesAvoidanceLayer27: String;
    public var layerNamesAvoidanceLayer28: String;
    public var layerNamesAvoidanceLayer29: String;
    public var layerNamesAvoidanceLayer30: String;
    public var layerNamesAvoidanceLayer31: String;
    public var layerNamesAvoidanceLayer32: String;
    public var memoryLimitsMessageQueueMaxSizeMb: Int;
    public var navigation2dDefaultCellSize: Float;
    public var navigation2dDefaultEdgeConnectionMargin: Float;
    public var navigation2dDefaultLinkConnectionRadius: Float;
    public var navigation2dUseEdgeConnections: Bool;
    public var navigation3dDefaultCellHeight: Float;
    public var navigation3dDefaultCellSize: Float;
    public var navigation3dDefaultEdgeConnectionMargin: Float;
    public var navigation3dDefaultLinkConnectionRadius: Float;
    public var navigation3dDefaultUp: Vector3;
    public var navigation3dMergeRasterizerCellScale: Float;
    public var navigation3dUseEdgeConnections: Bool;
    public var navigationAvoidanceThreadModelAvoidanceUseHighPriorityThreads: Bool;
    public var navigationAvoidanceThreadModelAvoidanceUseMultipleThreads: Bool;
    public var navigationBakingThreadModelBakingUseHighPriorityThreads: Bool;
    public var navigationBakingThreadModelBakingUseMultipleThreads: Bool;
    public var navigationBakingUseCrashPreventionChecks: Bool;
    public var navigationPathfindingMaxThreads: Int;
    public var navigationWorldMapUseAsyncIterations: Bool;
    public var networkLimitsDebuggerMaxCharsPerSecond: Int;
    public var networkLimitsDebuggerMaxErrorsPerSecond: Int;
    public var networkLimitsDebuggerMaxQueuedMessages: Int;
    public var networkLimitsDebuggerMaxWarningsPerSecond: Int;
    public var networkLimitsPacketPeerStreamMaxBufferPo2: Int;
    public var networkLimitsTcpConnectTimeoutSeconds: Int;
    public var networkLimitsWebrtcMaxChannelInBufferKb: Int;
    public var networkTlsCertificateBundleOverride: String;
    public var networkTlsEnableTlsV1.3: Bool;
    public var physics2dDefaultAngularDamp: Float;
    public var physics2dDefaultGravity: Float;
    public var physics2dDefaultGravityVector: Vector2;
    public var physics2dDefaultLinearDamp: Float;
    public var physics2dPhysicsEngine: String;
    public var physics2dRunOnSeparateThread: Bool;
    public var physics2dSleepThresholdAngular: Float;
    public var physics2dSleepThresholdLinear: Float;
    public var physics2dSolverContactMaxAllowedPenetration: Float;
    public var physics2dSolverContactMaxSeparation: Float;
    public var physics2dSolverContactRecycleRadius: Float;
    public var physics2dSolverDefaultConstraintBias: Float;
    public var physics2dSolverDefaultContactBias: Float;
    public var physics2dSolverSolverIterations: Int;
    public var physics2dTimeBeforeSleep: Float;
    public var physics3dDefaultAngularDamp: Float;
    public var physics3dDefaultGravity: Float;
    public var physics3dDefaultGravityVector: Vector3;
    public var physics3dDefaultLinearDamp: Float;
    public var physics3dPhysicsEngine: String;
    public var physics3dRunOnSeparateThread: Bool;
    public var physics3dSleepThresholdAngular: Float;
    public var physics3dSleepThresholdLinear: Float;
    public var physics3dSolverContactMaxAllowedPenetration: Float;
    public var physics3dSolverContactMaxSeparation: Float;
    public var physics3dSolverContactRecycleRadius: Float;
    public var physics3dSolverDefaultContactBias: Float;
    public var physics3dSolverSolverIterations: Int;
    public var physics3dTimeBeforeSleep: Float;
    public var physicsCommonEnableObjectPicking: Bool;
    public var physicsCommonMaxPhysicsStepsPerFrame: Int;
    public var physicsCommonPhysicsInterpolation: Bool;
    public var physicsCommonPhysicsJitterFix: Float;
    public var physicsCommonPhysicsTicksPerSecond: Int;
    public var physicsJoltPhysics3dCollisionsActiveEdgeThreshold: Float;
    public var physicsJoltPhysics3dCollisionsCollisionMarginFraction: Float;
    public var physicsJoltPhysics3dJointsWorldNode: Int;
    public var physicsJoltPhysics3dLimitsMaxAngularVelocity: Float;
    public var physicsJoltPhysics3dLimitsMaxBodies: Int;
    public var physicsJoltPhysics3dLimitsMaxBodyPairs: Int;
    public var physicsJoltPhysics3dLimitsMaxContactConstraints: Int;
    public var physicsJoltPhysics3dLimitsMaxLinearVelocity: Float;
    public var physicsJoltPhysics3dLimitsTemporaryMemoryBufferSize: Int;
    public var physicsJoltPhysics3dLimitsWorldBoundaryShapeSize: Float;
    public var physicsJoltPhysics3dMotionQueriesRecoveryAmount: Float;
    public var physicsJoltPhysics3dMotionQueriesRecoveryIterations: Int;
    public var physicsJoltPhysics3dMotionQueriesUseEnhancedInternalEdgeRemoval: Bool;
    public var physicsJoltPhysics3dQueriesEnableRayCastFaceIndex: Bool;
    public var physicsJoltPhysics3dQueriesUseEnhancedInternalEdgeRemoval: Bool;
    public var physicsJoltPhysics3dSimulationAllowSleep: Bool;
    public var physicsJoltPhysics3dSimulationAreasDetectStaticBodies: Bool;
    public var physicsJoltPhysics3dSimulationBaumgarteStabilizationFactor: Float;
    public var physicsJoltPhysics3dSimulationBodyPairContactCacheAngleThreshold: Float;
    public var physicsJoltPhysics3dSimulationBodyPairContactCacheDistanceThreshold: Float;
    public var physicsJoltPhysics3dSimulationBodyPairContactCacheEnabled: Bool;
    public var physicsJoltPhysics3dSimulationBounceVelocityThreshold: Float;
    public var physicsJoltPhysics3dSimulationContinuousCdMaxPenetration: Float;
    public var physicsJoltPhysics3dSimulationContinuousCdMovementThreshold: Float;
    public var physicsJoltPhysics3dSimulationGenerateAllKinematicContacts: Bool;
    public var physicsJoltPhysics3dSimulationPenetrationSlop: Float;
    public var physicsJoltPhysics3dSimulationPositionSteps: Int;
    public var physicsJoltPhysics3dSimulationSleepTimeThreshold: Float;
    public var physicsJoltPhysics3dSimulationSleepVelocityThreshold: Float;
    public var physicsJoltPhysics3dSimulationSoftBodyPointRadius: Float;
    public var physicsJoltPhysics3dSimulationSpeculativeContactDistance: Float;
    public var physicsJoltPhysics3dSimulationUseEnhancedInternalEdgeRemoval: Bool;
    public var physicsJoltPhysics3dSimulationVelocitySteps: Int;
    public var rendering2dBatchingItemBufferSize: Int;
    public var rendering2dBatchingUniformSetCacheSize: Int;
    public var rendering2dSdfOversize: Int;
    public var rendering2dSdfScale: Int;
    public var rendering2dShadowAtlasSize: Int;
    public var rendering2dSnapSnap2dTransformsToPixel: Bool;
    public var rendering2dSnapSnap2dVerticesToPixel: Bool;
    public var renderingAntiAliasingQualityMsaa2d: Int;
    public var renderingAntiAliasingQualityMsaa3d: Int;
    public var renderingAntiAliasingQualityScreenSpaceAa: Int;
    public var renderingAntiAliasingQualityUseDebanding: Bool;
    public var renderingAntiAliasingQualityUseTaa: Bool;
    public var renderingAntiAliasingScreenSpaceRoughnessLimiterAmount: Float;
    public var renderingAntiAliasingScreenSpaceRoughnessLimiterEnabled: Bool;
    public var renderingAntiAliasingScreenSpaceRoughnessLimiterLimit: Float;
    public var renderingCameraDepthOfFieldDepthOfFieldBokehQuality: Int;
    public var renderingCameraDepthOfFieldDepthOfFieldBokehShape: Int;
    public var renderingCameraDepthOfFieldDepthOfFieldUseJitter: Bool;
    public var renderingDriverDepthPrepassDisableForVendors: String;
    public var renderingDriverDepthPrepassEnable: Bool;
    public var renderingDriverThreadsThreadModel: Int;
    public var renderingEnvironmentDefaultsDefaultClearColor: Color;
    public var renderingEnvironmentDefaultsDefaultEnvironment: String;
    public var renderingEnvironmentGlowUpscaleMode: Int;
    public var renderingEnvironmentGlowUpscaleMode.mobile: Int;
    public var renderingEnvironmentScreenSpaceReflectionRoughnessQuality: Int;
    public var renderingEnvironmentSsaoAdaptiveTarget: Float;
    public var renderingEnvironmentSsaoBlurPasses: Int;
    public var renderingEnvironmentSsaoFadeoutFrom: Float;
    public var renderingEnvironmentSsaoFadeoutTo: Float;
    public var renderingEnvironmentSsaoHalfSize: Bool;
    public var renderingEnvironmentSsaoQuality: Int;
    public var renderingEnvironmentSsilAdaptiveTarget: Float;
    public var renderingEnvironmentSsilBlurPasses: Int;
    public var renderingEnvironmentSsilFadeoutFrom: Float;
    public var renderingEnvironmentSsilFadeoutTo: Float;
    public var renderingEnvironmentSsilHalfSize: Bool;
    public var renderingEnvironmentSsilQuality: Int;
    public var renderingEnvironmentSubsurfaceScatteringSubsurfaceScatteringDepthScale: Float;
    public var renderingEnvironmentSubsurfaceScatteringSubsurfaceScatteringQuality: Int;
    public var renderingEnvironmentSubsurfaceScatteringSubsurfaceScatteringScale: Float;
    public var renderingEnvironmentVolumetricFogUseFilter: Int;
    public var renderingEnvironmentVolumetricFogVolumeDepth: Int;
    public var renderingEnvironmentVolumetricFogVolumeSize: Int;
    public var renderingGlCompatibilityDriver: String;
    public var renderingGlCompatibilityDriver.android: String;
    public var renderingGlCompatibilityDriver.ios: String;
    public var renderingGlCompatibilityDriver.linuxbsd: String;
    public var renderingGlCompatibilityDriver.macos: String;
    public var renderingGlCompatibilityDriver.web: String;
    public var renderingGlCompatibilityDriver.windows: String;
    public var renderingGlCompatibilityFallbackToAngle: Bool;
    public var renderingGlCompatibilityFallbackToGles: Bool;
    public var renderingGlCompatibilityFallbackToNative: Bool;
    public var renderingGlCompatibilityForceAngleOnDevices: Array<Dynamic>;
    public var renderingGlCompatibilityItemBufferSize: Int;
    public var renderingGlCompatibilityNvidiaDisableThreadedOptimization: Bool;
    public var renderingGlobalIlluminationGiUseHalfResolution: Bool;
    public var renderingGlobalIlluminationSdfgiFramesToConverge: Int;
    public var renderingGlobalIlluminationSdfgiFramesToUpdateLights: Int;
    public var renderingGlobalIlluminationSdfgiProbeRayCount: Int;
    public var renderingGlobalIlluminationVoxelGiQuality: Int;
    public var renderingLightmappingBakePerformanceMaxRaysPerPass: Int;
    public var renderingLightmappingBakePerformanceMaxRaysPerProbePass: Int;
    public var renderingLightmappingBakePerformanceMaxTransparencyRays: Int;
    public var renderingLightmappingBakePerformanceRegionSize: Int;
    public var renderingLightmappingBakeQualityHighQualityProbeRayCount: Int;
    public var renderingLightmappingBakeQualityHighQualityRayCount: Int;
    public var renderingLightmappingBakeQualityLowQualityProbeRayCount: Int;
    public var renderingLightmappingBakeQualityLowQualityRayCount: Int;
    public var renderingLightmappingBakeQualityMediumQualityProbeRayCount: Int;
    public var renderingLightmappingBakeQualityMediumQualityRayCount: Int;
    public var renderingLightmappingBakeQualityUltraQualityProbeRayCount: Int;
    public var renderingLightmappingBakeQualityUltraQualityRayCount: Int;
    public var renderingLightmappingDenoisingDenoiser: Int;
    public var renderingLightmappingLightmapGiUseBicubicFilter: Bool;
    public var renderingLightmappingPrimitiveMeshesTexelSize: Float;
    public var renderingLightmappingProbeCaptureUpdateSpeed: Float;
    public var renderingLightsAndShadowsDirectionalShadow16Bits: Bool;
    public var renderingLightsAndShadowsDirectionalShadowSize: Int;
    public var renderingLightsAndShadowsDirectionalShadowSize.mobile: Int;
    public var renderingLightsAndShadowsDirectionalShadowSoftShadowFilterQuality: Int;
    public var renderingLightsAndShadowsDirectionalShadowSoftShadowFilterQuality.mobile: Int;
    public var renderingLightsAndShadowsPositionalShadowAtlas16Bits: Bool;
    public var renderingLightsAndShadowsPositionalShadowAtlasQuadrant0Subdiv: Int;
    public var renderingLightsAndShadowsPositionalShadowAtlasQuadrant1Subdiv: Int;
    public var renderingLightsAndShadowsPositionalShadowAtlasQuadrant2Subdiv: Int;
    public var renderingLightsAndShadowsPositionalShadowAtlasQuadrant3Subdiv: Int;
    public var renderingLightsAndShadowsPositionalShadowAtlasSize: Int;
    public var renderingLightsAndShadowsPositionalShadowAtlasSize.mobile: Int;
    public var renderingLightsAndShadowsPositionalShadowSoftShadowFilterQuality: Int;
    public var renderingLightsAndShadowsPositionalShadowSoftShadowFilterQuality.mobile: Int;
    public var renderingLightsAndShadowsTighterShadowCasterCulling: Bool;
    public var renderingLightsAndShadowsUsePhysicalLightUnits: Bool;
    public var renderingLimitsClusterBuilderMaxClusteredElements: Float;
    public var renderingLimitsGlobalShaderVariablesBufferSize: Int;
    public var renderingLimitsOpenglMaxLightsPerObject: Int;
    public var renderingLimitsOpenglMaxRenderableElements: Int;
    public var renderingLimitsOpenglMaxRenderableLights: Int;
    public var renderingLimitsSpatialIndexerThreadedCullMinimumInstances: Int;
    public var renderingLimitsSpatialIndexerUpdateIterationsPerFrame: Int;
    public var renderingLimitsTimeTimeRolloverSecs: Float;
    public var renderingMeshLodLodChangeThresholdPixels: Float;
    public var renderingOcclusionCullingBvhBuildQuality: Int;
    public var renderingOcclusionCullingJitterProjection: Bool;
    public var renderingOcclusionCullingOcclusionRaysPerThread: Int;
    public var renderingOcclusionCullingUseOcclusionCulling: Bool;
    public var renderingReflectionsReflectionAtlasReflectionCount: Int;
    public var renderingReflectionsReflectionAtlasReflectionSize: Int;
    public var renderingReflectionsReflectionAtlasReflectionSize.mobile: Int;
    public var renderingReflectionsSkyReflectionsFastFilterHighQuality: Bool;
    public var renderingReflectionsSkyReflectionsGgxSamples: Int;
    public var renderingReflectionsSkyReflectionsGgxSamples.mobile: Int;
    public var renderingReflectionsSkyReflectionsRoughnessLayers: Int;
    public var renderingReflectionsSkyReflectionsTextureArrayReflections: Bool;
    public var renderingReflectionsSkyReflectionsTextureArrayReflections.mobile: Bool;
    public var renderingRendererRenderingMethod: String;
    public var renderingRendererRenderingMethod.mobile: String;
    public var renderingRendererRenderingMethod.web: String;
    public var renderingRenderingDeviceD3d12AgilitySdkVersion: Int;
    public var renderingRenderingDeviceD3d12MaxMiscDescriptorsPerFrame: Int;
    public var renderingRenderingDeviceD3d12MaxResourceDescriptorsPerFrame: Int;
    public var renderingRenderingDeviceD3d12MaxSamplerDescriptorsPerFrame: Int;
    public var renderingRenderingDeviceDriver: String;
    public var renderingRenderingDeviceDriver.android: String;
    public var renderingRenderingDeviceDriver.ios: String;
    public var renderingRenderingDeviceDriver.linuxbsd: String;
    public var renderingRenderingDeviceDriver.macos: String;
    public var renderingRenderingDeviceDriver.windows: String;
    public var renderingRenderingDeviceFallbackToD3d12: Bool;
    public var renderingRenderingDeviceFallbackToOpengl3: Bool;
    public var renderingRenderingDeviceFallbackToVulkan: Bool;
    public var renderingRenderingDevicePipelineCacheEnable: Bool;
    public var renderingRenderingDevicePipelineCacheSaveChunkSizeMb: Float;
    public var renderingRenderingDeviceStagingBufferBlockSizeKb: Int;
    public var renderingRenderingDeviceStagingBufferMaxSizeMb: Int;
    public var renderingRenderingDeviceStagingBufferTextureDownloadRegionSizePx: Int;
    public var renderingRenderingDeviceStagingBufferTextureUploadRegionSizePx: Int;
    public var renderingRenderingDeviceVsyncFrameQueueSize: Int;
    public var renderingRenderingDeviceVsyncSwapchainImageCount: Int;
    public var renderingRenderingDeviceVulkanMaxDescriptorsPerPool: Int;
    public var renderingScaling3dFsrSharpness: Float;
    public var renderingScaling3dMode: Int;
    public var renderingScaling3dMode.ios: Int;
    public var renderingScaling3dMode.macos: Int;
    public var renderingScaling3dScale: Float;
    public var renderingShaderCompilerShaderCacheCompress: Bool;
    public var renderingShaderCompilerShaderCacheEnabled: Bool;
    public var renderingShaderCompilerShaderCacheStripDebug: Bool;
    public var renderingShaderCompilerShaderCacheStripDebug.release: Bool;
    public var renderingShaderCompilerShaderCacheUseZstdCompression: Bool;
    public var renderingShadingOverridesForceLambertOverBurley: Bool;
    public var renderingShadingOverridesForceLambertOverBurley.mobile: Bool;
    public var renderingShadingOverridesForceVertexShading: Bool;
    public var renderingTexturesCanvasTexturesDefaultTextureFilter: Int;
    public var renderingTexturesCanvasTexturesDefaultTextureRepeat: Int;
    public var renderingTexturesDecalsFilter: Int;
    public var renderingTexturesDefaultFiltersAnisotropicFilteringLevel: Int;
    public var renderingTexturesDefaultFiltersTextureMipmapBias: Float;
    public var renderingTexturesDefaultFiltersUseNearestMipmapFilter: Bool;
    public var renderingTexturesLightProjectorsFilter: Int;
    public var renderingTexturesLosslessCompressionForcePng: Bool;
    public var renderingTexturesVramCompressionCacheGpuCompressor: Bool;
    public var renderingTexturesVramCompressionCompressWithGpu: Bool;
    public var renderingTexturesVramCompressionImportEtc2Astc: Bool;
    public var renderingTexturesVramCompressionImportS3tcBptc: Bool;
    public var renderingTexturesWebpCompressionCompressionMethod: Int;
    public var renderingTexturesWebpCompressionLosslessCompressionFactor: Float;
    public var renderingViewportHdr2d: Bool;
    public var renderingViewportTransparentBackground: Bool;
    public var renderingVrsMode: Int;
    public var renderingVrsTexture: String;
    public var threadingWorkerPoolLowPriorityThreadRatio: Float;
    public var threadingWorkerPoolMaxThreads: Int;
    public var xrOpenxrBindingModifiersAnalogThreshold: Bool;
    public var xrOpenxrBindingModifiersDpadBinding: Bool;
    public var xrOpenxrDefaultActionMap: String;
    public var xrOpenxrEnabled: Bool;
    public var xrOpenxrEnvironmentBlendMode: Int;
    public var xrOpenxrExtensionsDebugMessageTypes: Int;
    public var xrOpenxrExtensionsDebugUtils: Int;
    public var xrOpenxrExtensionsEyeGazeInteraction: Bool;
    public var xrOpenxrExtensionsHandInteractionProfile: Bool;
    public var xrOpenxrExtensionsHandTracking: Bool;
    public var xrOpenxrExtensionsHandTrackingControllerDataSource: Bool;
    public var xrOpenxrExtensionsHandTrackingUnobstructedDataSource: Bool;
    public var xrOpenxrFormFactor: Int;
    public var xrOpenxrFoveationDynamic: Bool;
    public var xrOpenxrFoveationLevel: Int;
    public var xrOpenxrReferenceSpace: Int;
    public var xrOpenxrStartupAlert: Bool;
    public var xrOpenxrSubmitDepthBuffer: Bool;
    public var xrOpenxrViewConfiguration: Int;
    public var xrShadersEnabled: Bool;
    @:native("__new")
    public function new();
    public function addPropertyInfo(hint: Map<Dynamic, Dynamic>): Void;
    public function clear(name: String): Void;
    public function getGlobalClassList(): Dynamic;
    public function getOrder(name: String): Int;
    public function getSetting(name: String, ?defaultValue: Variant): Variant;
    public function getSettingWithOverride(name: StringName): Variant;
    public function globalizePath(path: String): String;
    public function hasSetting(name: String): Bool;
    public function loadResourcePack(pack: String, replaceFiles: Bool = true, offset: Int = 0): Bool;
    public function localizePath(path: String): String;
    public function save(): Int;
    public function saveCustom(file: String): Int;
    public function setAsBasic(name: String, basic: Bool): Void;
    public function setAsInternal(name: String, internal: Bool): Void;
    public function setInitialValue(name: String, value: Variant): Void;
    public function setOrder(name: String, position: Int): Void;
    public function setRestartIfChanged(name: String, restart: Bool): Void;
    public function setSetting(name: String, value: Variant): Void;
    public var settingsChanged: Event;
}
