package sunaba.godot;

import sunaba.core.Event;

@:native("godot.SpringBoneSimulator3D")
extern class SpringBoneSimulator3D extends SkeletonModifier3D {
    public var settingCount: Int;
    @:native("__new")
    public function new();
    public function areAllChildCollisionsEnabled(index: Int): Bool;
    public function clearCollisions(index: Int): Void;
    public function clearExcludeCollisions(index: Int): Void;
    public function clearSettings(): Void;
    public function getCenterBone(index: Int): Int;
    public function getCenterBoneName(index: Int): String;
    public function getCenterFrom(index: Int): Int;
    public function getCenterNode(index: Int): NodePath;
    public function getCollisionCount(index: Int): Int;
    public function getCollisionPath(index: Int, collision: Int): NodePath;
    public function getDrag(index: Int): Float;
    public function getDragDampingCurve(index: Int): Curve;
    public function getEndBone(index: Int): Int;
    public function getEndBoneDirection(index: Int): Int;
    public function getEndBoneLength(index: Int): Float;
    public function getEndBoneName(index: Int): String;
    public function getExcludeCollisionCount(index: Int): Int;
    public function getExcludeCollisionPath(index: Int, collision: Int): NodePath;
    public function getGravity(index: Int): Float;
    public function getGravityDampingCurve(index: Int): Curve;
    public function getGravityDirection(index: Int): Vector3;
    public function getJointBone(index: Int, joint: Int): Int;
    public function getJointBoneName(index: Int, joint: Int): String;
    public function getJointCount(index: Int): Int;
    public function getJointDrag(index: Int, joint: Int): Float;
    public function getJointGravity(index: Int, joint: Int): Float;
    public function getJointGravityDirection(index: Int, joint: Int): Vector3;
    public function getJointRadius(index: Int, joint: Int): Float;
    public function getJointRotationAxis(index: Int, joint: Int): Int;
    public function getJointStiffness(index: Int, joint: Int): Float;
    public function getRadius(index: Int): Float;
    public function getRadiusDampingCurve(index: Int): Curve;
    public function getRootBone(index: Int): Int;
    public function getRootBoneName(index: Int): String;
    public function getRotationAxis(index: Int): Int;
    public function getStiffness(index: Int): Float;
    public function getStiffnessDampingCurve(index: Int): Curve;
    public function isConfigIndividual(index: Int): Bool;
    public function isEndBoneExtended(index: Int): Bool;
    public function reset(): Void;
    public function setCenterBone(index: Int, bone: Int): Void;
    public function setCenterBoneName(index: Int, boneName: String): Void;
    public function setCenterFrom(index: Int, centerFrom: Int): Void;
    public function setCenterNode(index: Int, nodePath: NodePath): Void;
    public function setCollisionCount(index: Int, count: Int): Void;
    public function setCollisionPath(index: Int, collision: Int, nodePath: NodePath): Void;
    public function setDrag(index: Int, drag: Float): Void;
    public function setDragDampingCurve(index: Int, curve: Curve): Void;
    public function setEnableAllChildCollisions(index: Int, enabled: Bool): Void;
    public function setEndBone(index: Int, bone: Int): Void;
    public function setEndBoneDirection(index: Int, boneDirection: Int): Void;
    public function setEndBoneLength(index: Int, length: Float): Void;
    public function setEndBoneName(index: Int, boneName: String): Void;
    public function setExcludeCollisionCount(index: Int, count: Int): Void;
    public function setExcludeCollisionPath(index: Int, collision: Int, nodePath: NodePath): Void;
    public function setExtendEndBone(index: Int, enabled: Bool): Void;
    public function setGravity(index: Int, gravity: Float): Void;
    public function setGravityDampingCurve(index: Int, curve: Curve): Void;
    public function setGravityDirection(index: Int, gravityDirection: GdVector3): Void;
    public function setIndividualConfig(index: Int, enabled: Bool): Void;
    public function setJointDrag(index: Int, joint: Int, drag: Float): Void;
    public function setJointGravity(index: Int, joint: Int, gravity: Float): Void;
    public function setJointGravityDirection(index: Int, joint: Int, gravityDirection: GdVector3): Void;
    public function setJointRadius(index: Int, joint: Int, radius: Float): Void;
    public function setJointRotationAxis(index: Int, joint: Int, axis: Int): Void;
    public function setJointStiffness(index: Int, joint: Int, stiffness: Float): Void;
    public function setRadius(index: Int, radius: Float): Void;
    public function setRadiusDampingCurve(index: Int, curve: Curve): Void;
    public function setRootBone(index: Int, bone: Int): Void;
    public function setRootBoneName(index: Int, boneName: String): Void;
    public function setRotationAxis(index: Int, axis: Int): Void;
    public function setStiffness(index: Int, stiffness: Float): Void;
    public function setStiffnessDampingCurve(index: Int, curve: Curve): Void;
}
