package sunaba.godot;

import sunaba.core.Event;

@:native("godot.TreeItem")
extern class TreeItem extends Object {
    public var collapsed: Bool;
    public var customMinimumHeight: Int;
    public var disableFolding: Bool;
    public var visible: Bool;
    @:native("__new")
    public function new();
    public function addButton(column: Int, button: Texture2D, id: Int = -1, disabled: Bool = false, ?tooltipText: String): Void;
    public function addChild(child: TreeItem): Void;
    public function callRecursive(method: StringName): Void;
    public function clearButtons(): Void;
    public function clearCustomBgColor(column: Int): Void;
    public function clearCustomColor(column: Int): Void;
    public function createChild(index: Int = -1): TreeItem;
    public function deselect(column: Int): Void;
    public function eraseButton(column: Int, buttonIndex: Int): Void;
    public function getAutoTranslateMode(column: Int): Int;
    public function getAutowrapMode(column: Int): Int;
    public function getButton(column: Int, buttonIndex: Int): Texture2D;
    public function getButtonById(column: Int, id: Int): Int;
    public function getButtonColor(column: Int, id: Int): Color;
    public function getButtonCount(column: Int): Int;
    public function getButtonId(column: Int, buttonIndex: Int): Int;
    public function getButtonTooltipText(column: Int, buttonIndex: Int): String;
    public function getCellMode(column: Int): Int;
    public function getChild(index: Int): TreeItem;
    public function getChildCount(): Int;
    public function getChildren(): Dynamic;
    public function getCustomBgColor(column: Int): Color;
    public function getCustomColor(column: Int): Color;
    public function getCustomDrawCallback(column: Int): Callable;
    public function getCustomFont(column: Int): Font;
    public function getCustomFontSize(column: Int): Int;
    public function getExpandRight(column: Int): Bool;
    public function getFirstChild(): TreeItem;
    public function getIcon(column: Int): Texture2D;
    public function getIconMaxWidth(column: Int): Int;
    public function getIconModulate(column: Int): Color;
    public function getIconOverlay(column: Int): Texture2D;
    public function getIconRegion(column: Int): Rect2;
    public function getIndex(): Int;
    public function getLanguage(column: Int): String;
    public function getMetadata(column: Int): Variant;
    public function getNext(): TreeItem;
    public function getNextInTree(wrap: Bool = false): TreeItem;
    public function getNextVisible(wrap: Bool = false): TreeItem;
    public function getParent(): TreeItem;
    public function getPrev(): TreeItem;
    public function getPrevInTree(wrap: Bool = false): TreeItem;
    public function getPrevVisible(wrap: Bool = false): TreeItem;
    public function getRange(column: Int): Float;
    public function getRangeConfig(column: Int): Map<Dynamic, Dynamic>;
    public function getStructuredTextBidiOverride(column: Int): Int;
    public function getStructuredTextBidiOverrideOptions(column: Int): Array<Dynamic>;
    public function getSuffix(column: Int): String;
    public function getText(column: Int): String;
    public function getTextAlignment(column: Int): Int;
    public function getTextDirection(column: Int): Int;
    public function getTextOverrunBehavior(column: Int): Int;
    public function getTooltipText(column: Int): String;
    public function getTree(): Tree;
    public function isAnyCollapsed(onlyVisible: Bool = false): Bool;
    public function isButtonDisabled(column: Int, buttonIndex: Int): Bool;
    public function isChecked(column: Int): Bool;
    public function isCustomSetAsButton(column: Int): Bool;
    public function isEditMultiline(column: Int): Bool;
    public function isEditable(column: Int): Bool;
    public function isIndeterminate(column: Int): Bool;
    public function isSelectable(column: Int): Bool;
    public function isSelected(column: Int): Bool;
    public function isVisibleInTree(): Bool;
    public function moveAfter(item: TreeItem): Void;
    public function moveBefore(item: TreeItem): Void;
    public function propagateCheck(column: Int, emitSignal: Bool = true): Void;
    public function removeChild(child: TreeItem): Void;
    public function select(column: Int): Void;
    public function setAutoTranslateMode(column: Int, mode: Int): Void;
    public function setAutowrapMode(column: Int, autowrapMode: Int): Void;
    public function setButton(column: Int, buttonIndex: Int, button: Texture2D): Void;
    public function setButtonColor(column: Int, buttonIndex: Int, color: Color): Void;
    public function setButtonDisabled(column: Int, buttonIndex: Int, disabled: Bool): Void;
    public function setButtonTooltipText(column: Int, buttonIndex: Int, tooltip: String): Void;
    public function setCellMode(column: Int, mode: Int): Void;
    public function setChecked(column: Int, checked: Bool): Void;
    public function setCollapsedRecursive(enable: Bool): Void;
    public function setCustomAsButton(column: Int, enable: Bool): Void;
    public function setCustomBgColor(column: Int, color: Color, justOutline: Bool = false): Void;
    public function setCustomColor(column: Int, color: Color): Void;
    public function setCustomDraw(column: Int, object: Object, callback: StringName): Void;
    public function setCustomDrawCallback(column: Int, callback: Callable): Void;
    public function setCustomFont(column: Int, font: Font): Void;
    public function setCustomFontSize(column: Int, fontSize: Int): Void;
    public function setEditMultiline(column: Int, multiline: Bool): Void;
    public function setEditable(column: Int, enabled: Bool): Void;
    public function setExpandRight(column: Int, enable: Bool): Void;
    public function setIcon(column: Int, texture: Texture2D): Void;
    public function setIconMaxWidth(column: Int, width: Int): Void;
    public function setIconModulate(column: Int, modulate: Color): Void;
    public function setIconOverlay(column: Int, texture: Texture2D): Void;
    public function setIconRegion(column: Int, region: Rect2): Void;
    public function setIndeterminate(column: Int, indeterminate: Bool): Void;
    public function setLanguage(column: Int, language: String): Void;
    public function setMetadata(column: Int, meta: Variant): Void;
    public function setRange(column: Int, value: Float): Void;
    public function setRangeConfig(column: Int, min: Float, max: Float, step: Float, expr: Bool = false): Void;
    public function setSelectable(column: Int, selectable: Bool): Void;
    public function setStructuredTextBidiOverride(column: Int, parser: Int): Void;
    public function setStructuredTextBidiOverrideOptions(column: Int, args: Array<Dynamic>): Void;
    public function setSuffix(column: Int, text: String): Void;
    public function setText(column: Int, text: String): Void;
    public function setTextAlignment(column: Int, textAlignment: Int): Void;
    public function setTextDirection(column: Int, direction: Int): Void;
    public function setTextOverrunBehavior(column: Int, overrunBehavior: Int): Void;
    public function setTooltipText(column: Int, tooltip: String): Void;
    public function uncollapseTree(): Void;
}
